
spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 124.71.80.207
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    # 手动提交ack消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
server:
  port: 8081
