server:
  port: 9999
  servlet:
    session:
      # 让Tomcat只能从COOKIE中获取会话信息，这样，当没有Cookie时，URL也就不会被自动添加上 ;jsessionid=… 了。
      tracking-modes: COOKIE


spring:
  thymeleaf:
    # 关闭页面缓存，便于开发环境测试
    cache: false
    # 静态资源路径
    prefix: classpath:/templates/
    # 网页资源默认.html结尾
    mode: HTML